export type Continent = 'Europe' | 'Amérique du Nord' | 'Amérique du Sud' | 'Asie' | 'Océanie' | 'Afrique'

export interface CountryInfo {
  alpha2: string
  name: string
  continent: Continent
  flag: string
}

export const GEO_COUNTRIES: Record<string, CountryInfo> = {
  // Europe
  '008': { alpha2: 'AL', name: 'Albanie',           continent: 'Europe',    flag: '🇦🇱' },
  '040': { alpha2: 'AT', name: 'Autriche',           continent: 'Europe',    flag: '🇦🇹' },
  '056': { alpha2: 'BE', name: 'Belgique',           continent: 'Europe',    flag: '🇧🇪' },
  '070': { alpha2: 'BA', name: 'Bosnie',             continent: 'Europe',    flag: '🇧🇦' },
  '100': { alpha2: 'BG', name: 'Bulgarie',           continent: 'Europe',    flag: '🇧🇬' },
  '112': { alpha2: 'BY', name: 'Biélorussie',        continent: 'Europe',    flag: '🇧🇾' },
  '191': { alpha2: 'HR', name: 'Croatie',            continent: 'Europe',    flag: '🇭🇷' },
  '196': { alpha2: 'CY', name: 'Chypre',             continent: 'Europe',    flag: '🇨🇾' },
  '203': { alpha2: 'CZ', name: 'Tchéquie',           continent: 'Europe',    flag: '🇨🇿' },
  '208': { alpha2: 'DK', name: 'Danemark',           continent: 'Europe',    flag: '🇩🇰' },
  '233': { alpha2: 'EE', name: 'Estonie',            continent: 'Europe',    flag: '🇪🇪' },
  '246': { alpha2: 'FI', name: 'Finlande',           continent: 'Europe',    flag: '🇫🇮' },
  '250': { alpha2: 'FR', name: 'France',             continent: 'Europe',    flag: '🇫🇷' },
  '276': { alpha2: 'DE', name: 'Allemagne',          continent: 'Europe',    flag: '🇩🇪' },
  '300': { alpha2: 'GR', name: 'Grèce',              continent: 'Europe',    flag: '🇬🇷' },
  '348': { alpha2: 'HU', name: 'Hongrie',            continent: 'Europe',    flag: '🇭🇺' },
  '352': { alpha2: 'IS', name: 'Islande',            continent: 'Europe',    flag: '🇮🇸' },
  '372': { alpha2: 'IE', name: 'Irlande',            continent: 'Europe',    flag: '🇮🇪' },
  '380': { alpha2: 'IT', name: 'Italie',             continent: 'Europe',    flag: '🇮🇹' },
  '428': { alpha2: 'LV', name: 'Lettonie',           continent: 'Europe',    flag: '🇱🇻' },
  '440': { alpha2: 'LT', name: 'Lituanie',           continent: 'Europe',    flag: '🇱🇹' },
  '442': { alpha2: 'LU', name: 'Luxembourg',         continent: 'Europe',    flag: '🇱🇺' },
  '807': { alpha2: 'MK', name: 'Macédoine du Nord',  continent: 'Europe',    flag: '🇲🇰' },
  '470': { alpha2: 'MT', name: 'Malte',              continent: 'Europe',    flag: '🇲🇹' },
  '498': { alpha2: 'MD', name: 'Moldavie',           continent: 'Europe',    flag: '🇲🇩' },
  '499': { alpha2: 'ME', name: 'Monténégro',         continent: 'Europe',    flag: '🇲🇪' },
  '528': { alpha2: 'NL', name: 'Pays-Bas',           continent: 'Europe',    flag: '🇳🇱' },
  '578': { alpha2: 'NO', name: 'Norvège',            continent: 'Europe',    flag: '🇳🇴' },
  '616': { alpha2: 'PL', name: 'Pologne',            continent: 'Europe',    flag: '🇵🇱' },
  '620': { alpha2: 'PT', name: 'Portugal',           continent: 'Europe',    flag: '🇵🇹' },
  '642': { alpha2: 'RO', name: 'Roumanie',           continent: 'Europe',    flag: '🇷🇴' },
  '643': { alpha2: 'RU', name: 'Russie',             continent: 'Europe',    flag: '🇷🇺' },
  '688': { alpha2: 'RS', name: 'Serbie',             continent: 'Europe',    flag: '🇷🇸' },
  '703': { alpha2: 'SK', name: 'Slovaquie',          continent: 'Europe',    flag: '🇸🇰' },
  '705': { alpha2: 'SI', name: 'Slovénie',           continent: 'Europe',    flag: '🇸🇮' },
  '724': { alpha2: 'ES', name: 'Espagne',            continent: 'Europe',    flag: '🇪🇸' },
  '752': { alpha2: 'SE', name: 'Suède',              continent: 'Europe',    flag: '🇸🇪' },
  '756': { alpha2: 'CH', name: 'Suisse',             continent: 'Europe',    flag: '🇨🇭' },
  '804': { alpha2: 'UA', name: 'Ukraine',            continent: 'Europe',    flag: '🇺🇦' },
  '826': { alpha2: 'GB', name: 'Royaume-Uni',        continent: 'Europe',    flag: '🇬🇧' },

  // Amérique du Nord
  '124': { alpha2: 'CA', name: 'Canada',             continent: 'Amérique du Nord', flag: '🇨🇦' },
  '188': { alpha2: 'CR', name: 'Costa Rica',         continent: 'Amérique du Nord', flag: '🇨🇷' },
  '192': { alpha2: 'CU', name: 'Cuba',               continent: 'Amérique du Nord', flag: '🇨🇺' },
  '320': { alpha2: 'GT', name: 'Guatemala',          continent: 'Amérique du Nord', flag: '🇬🇹' },
  '388': { alpha2: 'JM', name: 'Jamaïque',           continent: 'Amérique du Nord', flag: '🇯🇲' },
  '484': { alpha2: 'MX', name: 'Mexique',            continent: 'Amérique du Nord', flag: '🇲🇽' },
  '591': { alpha2: 'PA', name: 'Panama',             continent: 'Amérique du Nord', flag: '🇵🇦' },
  '840': { alpha2: 'US', name: 'États-Unis',         continent: 'Amérique du Nord', flag: '🇺🇸' },

  // Amérique du Sud
  '032': { alpha2: 'AR', name: 'Argentine',          continent: 'Amérique du Sud', flag: '🇦🇷' },
  '068': { alpha2: 'BO', name: 'Bolivie',            continent: 'Amérique du Sud', flag: '🇧🇴' },
  '076': { alpha2: 'BR', name: 'Brésil',             continent: 'Amérique du Sud', flag: '🇧🇷' },
  '152': { alpha2: 'CL', name: 'Chili',              continent: 'Amérique du Sud', flag: '🇨🇱' },
  '170': { alpha2: 'CO', name: 'Colombie',           continent: 'Amérique du Sud', flag: '🇨🇴' },
  '218': { alpha2: 'EC', name: 'Équateur',           continent: 'Amérique du Sud', flag: '🇪🇨' },
  '600': { alpha2: 'PY', name: 'Paraguay',           continent: 'Amérique du Sud', flag: '🇵🇾' },
  '604': { alpha2: 'PE', name: 'Pérou',              continent: 'Amérique du Sud', flag: '🇵🇪' },
  '858': { alpha2: 'UY', name: 'Uruguay',            continent: 'Amérique du Sud', flag: '🇺🇾' },
  '862': { alpha2: 'VE', name: 'Venezuela',          continent: 'Amérique du Sud', flag: '🇻🇪' },

  // Asie
  '050': { alpha2: 'BD', name: 'Bangladesh',         continent: 'Asie',      flag: '🇧🇩' },
  '156': { alpha2: 'CN', name: 'Chine',              continent: 'Asie',      flag: '🇨🇳' },
  '356': { alpha2: 'IN', name: 'Inde',               continent: 'Asie',      flag: '🇮🇳' },
  '360': { alpha2: 'ID', name: 'Indonésie',          continent: 'Asie',      flag: '🇮🇩' },
  '364': { alpha2: 'IR', name: 'Iran',               continent: 'Asie',      flag: '🇮🇷' },
  '368': { alpha2: 'IQ', name: 'Irak',               continent: 'Asie',      flag: '🇮🇶' },
  '376': { alpha2: 'IL', name: 'Israël',             continent: 'Asie',      flag: '🇮🇱' },
  '392': { alpha2: 'JP', name: 'Japon',              continent: 'Asie',      flag: '🇯🇵' },
  '398': { alpha2: 'KZ', name: 'Kazakhstan',         continent: 'Asie',      flag: '🇰🇿' },
  '408': { alpha2: 'KP', name: 'Corée du Nord',      continent: 'Asie',      flag: '🇰🇵' },
  '410': { alpha2: 'KR', name: 'Corée du Sud',       continent: 'Asie',      flag: '🇰🇷' },
  '414': { alpha2: 'KW', name: 'Koweït',             continent: 'Asie',      flag: '🇰🇼' },
  '418': { alpha2: 'LA', name: 'Laos',               continent: 'Asie',      flag: '🇱🇦' },
  '458': { alpha2: 'MY', name: 'Malaisie',           continent: 'Asie',      flag: '🇲🇾' },
  '496': { alpha2: 'MN', name: 'Mongolie',           continent: 'Asie',      flag: '🇲🇳' },
  '104': { alpha2: 'MM', name: 'Myanmar',            continent: 'Asie',      flag: '🇲🇲' },
  '524': { alpha2: 'NP', name: 'Népal',              continent: 'Asie',      flag: '🇳🇵' },
  '512': { alpha2: 'OM', name: 'Oman',               continent: 'Asie',      flag: '🇴🇲' },
  '586': { alpha2: 'PK', name: 'Pakistan',           continent: 'Asie',      flag: '🇵🇰' },
  '608': { alpha2: 'PH', name: 'Philippines',        continent: 'Asie',      flag: '🇵🇭' },
  '634': { alpha2: 'QA', name: 'Qatar',              continent: 'Asie',      flag: '🇶🇦' },
  '682': { alpha2: 'SA', name: 'Arabie Saoudite',    continent: 'Asie',      flag: '🇸🇦' },
  '702': { alpha2: 'SG', name: 'Singapour',          continent: 'Asie',      flag: '🇸🇬' },
  '144': { alpha2: 'LK', name: 'Sri Lanka',          continent: 'Asie',      flag: '🇱🇰' },
  '158': { alpha2: 'TW', name: 'Taïwan',             continent: 'Asie',      flag: '🇹🇼' },
  '764': { alpha2: 'TH', name: 'Thaïlande',          continent: 'Asie',      flag: '🇹🇭' },
  '792': { alpha2: 'TR', name: 'Turquie',            continent: 'Asie',      flag: '🇹🇷' },
  '784': { alpha2: 'AE', name: 'Émirats Arabes Unis',continent: 'Asie',      flag: '🇦🇪' },
  '704': { alpha2: 'VN', name: 'Vietnam',            continent: 'Asie',      flag: '🇻🇳' },
  '887': { alpha2: 'YE', name: 'Yémen',              continent: 'Asie',      flag: '🇾🇪' },

  // Afrique
  '012': { alpha2: 'DZ', name: 'Algérie',            continent: 'Afrique',   flag: '🇩🇿' },
  '024': { alpha2: 'AO', name: 'Angola',             continent: 'Afrique',   flag: '🇦🇴' },
  '072': { alpha2: 'BW', name: 'Botswana',           continent: 'Afrique',   flag: '🇧🇼' },
  '120': { alpha2: 'CM', name: 'Cameroun',           continent: 'Afrique',   flag: '🇨🇲' },
  '140': { alpha2: 'CF', name: 'Rép. Centrafricaine',continent: 'Afrique',   flag: '🇨🇫' },
  '148': { alpha2: 'TD', name: 'Tchad',              continent: 'Afrique',   flag: '🇹🇩' },
  '178': { alpha2: 'CG', name: 'Congo',              continent: 'Afrique',   flag: '🇨🇬' },
  '180': { alpha2: 'CD', name: 'RD Congo',           continent: 'Afrique',   flag: '🇨🇩' },
  '818': { alpha2: 'EG', name: 'Égypte',             continent: 'Afrique',   flag: '🇪🇬' },
  '231': { alpha2: 'ET', name: 'Éthiopie',           continent: 'Afrique',   flag: '🇪🇹' },
  '266': { alpha2: 'GA', name: 'Gabon',              continent: 'Afrique',   flag: '🇬🇦' },
  '288': { alpha2: 'GH', name: 'Ghana',              continent: 'Afrique',   flag: '🇬🇭' },
  '384': { alpha2: 'CI', name: "Côte d'Ivoire",      continent: 'Afrique',   flag: '🇨🇮' },
  '404': { alpha2: 'KE', name: 'Kenya',              continent: 'Afrique',   flag: '🇰🇪' },
  '434': { alpha2: 'LY', name: 'Libye',              continent: 'Afrique',   flag: '🇱🇾' },
  '450': { alpha2: 'MG', name: 'Madagascar',         continent: 'Afrique',   flag: '🇲🇬' },
  '454': { alpha2: 'MW', name: 'Malawi',             continent: 'Afrique',   flag: '🇲🇼' },
  '466': { alpha2: 'ML', name: 'Mali',               continent: 'Afrique',   flag: '🇲🇱' },
  '504': { alpha2: 'MA', name: 'Maroc',              continent: 'Afrique',   flag: '🇲🇦' },
  '508': { alpha2: 'MZ', name: 'Mozambique',         continent: 'Afrique',   flag: '🇲🇿' },
  '516': { alpha2: 'NA', name: 'Namibie',            continent: 'Afrique',   flag: '🇳🇦' },
  '562': { alpha2: 'NE', name: 'Niger',              continent: 'Afrique',   flag: '🇳🇪' },
  '566': { alpha2: 'NG', name: 'Nigéria',            continent: 'Afrique',   flag: '🇳🇬' },
  '646': { alpha2: 'RW', name: 'Rwanda',             continent: 'Afrique',   flag: '🇷🇼' },
  '686': { alpha2: 'SN', name: 'Sénégal',            continent: 'Afrique',   flag: '🇸🇳' },
  '706': { alpha2: 'SO', name: 'Somalie',            continent: 'Afrique',   flag: '🇸🇴' },
  '710': { alpha2: 'ZA', name: 'Afrique du Sud',     continent: 'Afrique',   flag: '🇿🇦' },
  '729': { alpha2: 'SD', name: 'Soudan',             continent: 'Afrique',   flag: '🇸🇩' },
  '728': { alpha2: 'SS', name: 'Soudan du Sud',      continent: 'Afrique',   flag: '🇸🇸' },
  '788': { alpha2: 'TN', name: 'Tunisie',            continent: 'Afrique',   flag: '🇹🇳' },
  '800': { alpha2: 'UG', name: 'Ouganda',            continent: 'Afrique',   flag: '🇺🇬' },
  '834': { alpha2: 'TZ', name: 'Tanzanie',           continent: 'Afrique',   flag: '🇹🇿' },
  '894': { alpha2: 'ZM', name: 'Zambie',             continent: 'Afrique',   flag: '🇿🇲' },
  '716': { alpha2: 'ZW', name: 'Zimbabwe',           continent: 'Afrique',   flag: '🇿🇼' },

  // Océanie
  '036': { alpha2: 'AU', name: 'Australie',          continent: 'Océanie',   flag: '🇦🇺' },
  '242': { alpha2: 'FJ', name: 'Fidji',              continent: 'Océanie',   flag: '🇫🇯' },
  '554': { alpha2: 'NZ', name: 'Nouvelle-Zélande',   continent: 'Océanie',   flag: '🇳🇿' },
  '598': { alpha2: 'PG', name: 'Papouasie',          continent: 'Océanie',   flag: '🇵🇬' },
}

export const CONTINENTS: Continent[] = ['Europe', 'Amérique du Nord', 'Amérique du Sud', 'Asie', 'Océanie', 'Afrique']
